name: Build & Release Static Binary

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build Static Linux Binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build in Alpine Container
        uses: docker://golang:alpine
        with:
          entrypoint: /bin/sh
          args: -c "apk add --no-cache build-base git && && go mod init InferenceProfiler && go build -C ./src -ldflags '-linkmode external -extldflags \"-static\" -s -w' -o container-profiler ."
        env:
          CGO_ENABLED: 1

      - name: Verify Static Build
        run: |
          # Use 'file' on the host to verify the binary artifact
          if ! file container-profiler | grep -q "statically linked"; then
            echo "Error: Binary is not statically linked"
            exit 1
          fi

      - name: Update Nightly Release
        uses: softprops/action-gh-release@v2
        with:
          name: Nightly Build
          tag_name: nightly
          files: container-profiler
          prerelease: true
          make_latest: true